name: test

on:
  - pull_request
  - push

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Test this PR
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROCKET_CHAT_HOOK: "jx3Xu73EQWA54bZwh/PBaQsa9NAD4zfCXLzvfWPpvPELi5jDfStqTfmuzuxkYqkhMv"
	  days_since_update: 0
          message: 'Test'
